# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='more_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='more name'),
        ),
    ]
