# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_profile_more_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'created', 'ordering': ('-created',), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
